# Generated by Django 4.0.4 on 2022-05-27 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_order_totalprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='shippingPrice',
        ),
    ]
