# Generated by Django 4.0.4 on 2022-05-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_order_isdelivered_alter_order_ispaid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stripe_session_id',
            field=models.TextField(blank=True),
        ),
    ]
