# Generated by Django 4.0.4 on 2022-06-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_order_stripe_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='/resolution.jpg', null=True, upload_to='image/'),
        ),
    ]
